name: Docs
on: [push, pull_request]
jobs:
  BuildDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs] --use-feature=in-tree-build
      - name: Run Sphinx
        working-directory: ./docs
        run: make html SPHINXOPTS="--keep-going"
      - name: Upload docs to docs.icecube.aq
        working-directory: ./docs
        env:
          ICECUBE_PASSWORD: ${{ secrets.ICECUBE_PASSWORD }}
        run: ./upload-docs.sh
