name: Tests
on: [push, pull_request]
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install SimWeights
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit
        python -m flit install --symlink --deps=production --extras=test,dev
    - name: Download Test Data
      run: curl -u icecube:${{secrets.ICECUBE_PASSWORD}} https://convey.icecube.wisc.edu/data/user/kmeagher/simweights_testdata.tar.gz | tar xz
    - name: Run Tests
      env:
        SIMWEIGHTS_TESTDATA: .
      run: |
        pre-commit run --all-files
        pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        verbose: true
