name: Unit Tests
on: [push, pull_request]
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          - python-version: 3.8
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy h5py tables pandas pytest pytest-isort pytest-black pytest-flake8 pytest-pylint
          pip install .
      - name: Unit Tests
        run: |
          pytest --isort --black --flake8 --pylint --pylint-ignore=tests