name: Tests
on: [push, pull_request]
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Apt-Get Install Deps
        if: ${{ contains( matrix.os, 'ubuntu') && contains( matrix.python-version, '3.10') }}
        run: sudo apt-get install libblosc-dev libhdf5-dev
      - name: HomeBrew Install Deps
        if: ${{ contains( matrix.os, 'macos') && ( contains( matrix.python-version, '3.9') || contains( matrix.python-version, '3.10') ) }}
        run: brew install c-blosc hdf5
      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip
      - name: Install PyTables from GitHub
        if: ${{ contains( matrix.python-version, '3.10') }} 
        run: |
          python3 -m pip install cython
          python3 -m pip install git+https://github.com/PyTables/PyTables
      - name: Install SimWeights
        run: pip install .[test] --use-feature=in-tree-build
      - name: Run Tests
        run: pytest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          verbose: true
